export ZSH="/Users/anhmv/.oh-my-zsh"

ZSH_THEME="avit"
prompt_context(){}

source $ZSH/oh-my-zsh.sh
source ~/.bash_profile

DEFAULT_USER="anhmv"
DISABLE_UNTRACKED_FILES_DIRTY=true

alias vim="nvim"

plugins=(git node brew tmux fzf)

ZSH_TMUX_AUTOCONNECT="true"
tmux source-file ~/.tmux.conf

#
# Set default editor to nvim
export EDITOR='nvim'
export NVIM_TUI_ENABLE_TRUE_COLOR=1

export FZF_DEFAULT_COMMAND='rg --files --hidden --follow --no-ignore-vcs'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
